[package]
name = "rust-cheddar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "core"
path = "src/core/lib.rs"
test = true
crate-type = ["lib"]

[profile.bench]
debug = true

[dependencies]
